-- scripts/extract_icons.lua
-- Helper to extract the full icon tables from an installed nvim-web-devicons
-- Usage (from repo root):
--   nvim --headless -c 'lua require("scripts.extract_icons").run()' -c qa
--
-- This will write lua/volt/icons/full.lua. Requires nvim-web-devicons to be installed
-- in your runtimepath.

local M = {}

local function safe_write(path, content)
  local f, err = io.open(path, "w")
  if not f then
    return nil, err
  end
  f:write(content)
  f:close()
  return true
end

function M.run()
  local ok, devicons = pcall(require, "nvim-web-devicons")
  if not ok or not devicons then
    return error("nvim-web-devicons not found in runtimepath")
  end

  -- Try to get maps from the plugin API or fall back to known internals
  local by_ext = {}
  local by_name = {}

  -- Attempt to use plugin-provided functions if available
  if devicons.get_icons then
    -- some versions expose a combined table
    local tbl = devicons.get_icons()
    if tbl.by_extension then by_ext = tbl.by_extension end
    if tbl.by_filename then by_name = tbl.by_filename end
  else
    -- try common functions / internals
    if devicons.get_icon_by_filetype then
      -- Not standard; skip
    end
    -- Try reading exported tables (different plugin versions vary)
    by_ext = devicons.icons_by_file_extension or devicons.get_icons_by_extension and devicons.get_icons_by_extension() or by_ext
    by_name = devicons.icons_by_filename or devicons.get_icons_by_filename and devicons.get_icons_by_filename() or by_name
  end

  -- Fallback: if those calls returned functions/unknown, ensure final tables
  by_ext = by_ext or {}
  by_name = by_name or {}

  local content = {}
  table.insert(content, "-- Auto-generated by scripts/extract_icons.lua")
  table.insert(content, "return {")
  table.insert(content, "  by_extension = " .. vim.inspect(by_ext) .. ",")
  table.insert(content, "  by_filename = " .. vim.inspect(by_name) .. ",")
  table.insert(content, "}")

  local ok, err = safe_write("lua/volt/icons/full.lua", table.concat(content, "\n"))
  if not ok then
    error("Failed to write lua/volt/icons/full.lua: " .. tostring(err))
  end
  print("Wrote lua/volt/icons/full.lua")
end

return M
